### ISSUE TITLE
Causes crash if Facebook not accessible via network

### ISSUE THREAD

**Issue by aesidau** [Thuzi/facebook-node-sdk#104]
Accessing the Facebook API is only one of the things my application does, but if it can't get to Facebook the whole application crashes because an Error is thrown that can't be caught by my application. Here is what I see in the log:

```
{ [Error: getaddrinfo ENOTFOUND www.flickr.com]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'www.flickr.com' }
/Users/aesidau/src/myapplication/node_modules/flickrapi/src/utils.js:141
      var constituents = body.split("&"),
                             ^
TypeError: Cannot read property 'split' of undefined
    at Object.module.exports.parseRestResponse (/Users/aesidau/src/myapplication/node_modules/flickrapi/src/utils.js:141:30)
    at Request._callback (/Users/aesidau/src/myapplication/node_modules/flickrapi/src/auth/request.js:34:24)
    at self.callback (/Users/aesidau/src/myapplication/node_modules/flickrapi/node_modules/request/index.js:148:22)
    at Request.emit (events.js:107:17)
    at ClientRequest.self.clientErrorHandler (/Users/aesidau/src/myapplication/node_modules/flickrapi/node_modules/request/index.js:258:10)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketErrorListener (_http_client.js:271:9)
    at TLSSocket.emit (events.js:129:20)
    at net.js:950:16
    at process._tickCallback (node.js:355:11)
```

This can be fixed by updating the following code in the src/auth/request.js file:

``` javascript
    request.get(flickrURL, function(error, response, body) {
      if(error) {
        console.log(error);
      }
```

and replacing it with:

``` javascript
    request.get(flickrURL, function(error, response, body) {
      if(error) {
        console.log(error);
        return requestCompleted(error);
      }
```

Actually, only a single line is added, to ensure that upon an error the function finishes up rather than continuing on without a valid response or body object.

**Comment by dantman** [comment]
This bug appears to be reported to the wrong module. Your example contains flickrURL, is an ENOTFOUND for flickr.com, and comes from node_modules/flickrapi/.

**Comment by aesidau** [comment]
Sorry - yes, you're absolutely right. Please ignore.
