### ISSUE TITLE
Error: getaddrinfo ENOTFOUND graph.accountkit.com graph.accountkit.com:443

### ISSUE THREAD

**Issue by FourKnife** [Thuzi/facebook-node-sdk#122]
Hi, when I try to get access_token, I get this error:
```
Error: getaddrinfo ENOTFOUND graph.accountkit.com graph.accountkit.com:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)
```
But I can get correct info by typing  url in browser. 

So, I'm not sure if my proxy's problem

**Comment by dantman** [comment]
Neither this obsolete SDK or the [newer version](https://github.com/node-facebook/facebook-node-sdk) make any calls to accountkit so this doesn't have anything to do with the library.
